_security_logout:
    resource: security.route_loader.logout
    type: service

api_auth_login:
    path: /api/auth/login
    methods: ['POST']

api_auth_logout:
    path: /api/auth/logout
    methods: ['POST']
