name: pull-request

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug
          extensions: mbstring, intl, dom, json, pdo, pdo_pgsql

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-interaction --no-progress --prefer-dist

      - name: PHP CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

      - name: PHP Mess Detector (phpmd)
        run: vendor/bin/phpmd src text phpmd_ruleset.xml

      - name: PHPStan
        run: vendor/bin/phpstan analyse --configuration phpstan.neon --no-progress --memory-limit=-1

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          coverage: xdebug
          extensions: mbstring, intl, dom, json, pdo, pdo_pgsql

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit (Unit only) with coverage
        run: vendor/bin/phpunit -c phpunit.dist.xml tests/Unit --coverage-clover coverage.xml --colors=always

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.xml
          if-no-files-found: error
          retention-days: 7

  status-comment:
    name: Post status comment
    needs: [static-analysis, tests]
    if: ${{ success() }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: .

      - name: Extract coverage percentage
        id: cov
        run: |
          php -r '$x=simplexml_load_file("coverage.xml");$m=$x->project->metrics; $tot=(int)$m["statements"]; $cov=(int)$m["coveredstatements"]; $pct=$tot?round($cov/$tot*100,2):0; file_put_contents(getenv("GITHUB_OUTPUT"), "coverage=$pct\n", FILE_APPEND);'

      - name: Comment on PR with status
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ Static analysis: passed
            ✅ Tests: passed
            📊 Unit test coverage: ${{ steps.cov.outputs.coverage }}%


